from fpdf import FPDF
import re

class MarkdownPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        
    def add_markdown_text(self, text: str):
        """Simple markdown to PDF converter"""
        lines = text.split('\n')
        
        for line in lines:
            line = line.strip()
            
            if not line:
                self.ln(4)
                continue
                
            # Headers
            if line.startswith('###'):
                self.set_font("Arial", "B", 12)
                self.multi_cell(0, 7, line[3:].strip(), ln=1)
            elif line.startswith('##'):
                self.set_font("Arial", "B", 14)
                self.multi_cell(0, 8, line[2:].strip(), ln=1)
            elif line.startswith('#'):
                self.set_font("Arial", "B", 16)
                self.multi_cell(0, 9, line[1:].strip(), ln=1)
            # Bullet points
            elif line.startswith('•') or line.startswith('-') or line.startswith('*'):
                self.set_font("Arial", "", 11)
                # Indent bullet points
                self.cell(5, 6, "", ln=0)  # Indent
                self.multi_cell(0, 6, line, ln=1)
            # Bold text (simple version)
            elif '**' in line:
                self.set_font("Arial", "", 11)
                # Simple bold replacement
                clean_line = re.sub(r'\*\*(.*?)\*\*', r'\1', line)
                self.multi_cell(0, 6, clean_line, ln=1)
            # Regular text
            else:
                self.set_font("Arial", "", 11)
                self.multi_cell(0, 6, line, ln=1)

def generate_analysis_pdf(
    idea: str, plan: str, market: str, competition: str, financial: str,
    gtm: str, risks: str, critic: str, final_report: str
) -> bytes | None:
    try:
        pdf = MarkdownPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", "B", 20)
        pdf.cell(0, 12, "Business Idea Analysis Report", ln=1, align='C')
        pdf.ln(5)
        
        # Business Idea
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 8, "Business Idea", ln=1)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(0, 6, idea)
        pdf.ln(4)
        
        # Analysis sections
        sections = [
            ("Analysis Plan", plan),
            ("Market Analysis", market),
            ("Competition Analysis", competition),
            ("Financial Feasibility", financial),
            ("Go-to-Market Strategy", gtm),
            ("Risk Analysis", risks),
            ("Critical Review", critic),
            ("Executive Summary & Synthesis", final_report)
        ]
        
        for title, content in sections:
            if content and content.strip():
                pdf.add_page()
                pdf.set_font("Arial", "B", 16)
                pdf.cell(0, 10, title, ln=1)
                pdf.ln(3)
                
                # Use markdown parser for final report, regular text for others
                if title == "Executive Summary & Synthesis":
                    pdf.add_markdown_text(content)
                else:
                    pdf.set_font("Arial", "", 11)
                    pdf.multi_cell(0, 6, content)
                pdf.ln(4)
        
        # Footer on last page
        pdf.ln(10)
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 6, "Generated by Business Idea Analyzer - Powered by GPT-4", ln=1, align='C')
        
        return pdf.output(dest="S").encode("latin-1")
        
    except Exception as e:
        print(f"PDF generation error: {e}")
        # Return a simple fallback PDF
        try:
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", "B", 16)
            pdf.cell(0, 10, "Business Idea Analysis Report", ln=1)
            pdf.set_font("Arial", "", 12)
            pdf.multi_cell(0, 8, f"Business Idea: {idea}\n\nPDF generation encountered an error. Please copy the analysis from the web interface.")
            return pdf.output(dest="S").encode("latin-1")
        except:
            return None
